version: '3'
services:
  train_builder:
    container_name: train_builder
    build: .
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3.9-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=admin"
      - "RABBITMQ_DEFAULT_VHOST=/"
      - "RABBITMQ_ERLANG_COOKIE=admin"
      - "RABBITMQ_NODENAME=rabbit"