version: '3'
services:
  train_builder:
    container_name: train_builder
    build: .
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"