version: '3'
services:
  train_builder:
    container_name: train_builder
    build: .
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./build_dir:/home/build_dir
    env_file:
      - .env