from io import BytesIO
import tarfile
import docker
import subprocess
import json
from typing import List, Tuple



class ImageHandler:
    def __init__(self, docker_client: docker.client.DockerClient) -> None:
        self.client = docker_client

    def image_to_train(self, message: dict, img_name: str) -> dict:
        pass

    def validate_image(self, message: dict) -> Tuple[int, str]:

        # Extract the image names from the message and download obtain the image objects
        master_img_name = message["master_image"]
        submission_img_name = message["proposal_image"]
        # Get the images
        master_img = self._get_image(master_img_name)
        submission_img = self._get_image(submission_img_name)
        # Compare image histories
        history_diff = self._compare_image_history(master_img, submission_img)
        print(history_diff)
        hist_valid = self._validate_history_diff(history_diff)
        # compare image file systems
        if hist_valid:
            code, msg = self._compare_image_file_system(master_img_name, submission_img_name)
            self._extract_immutable_files(submission_img_name)
            if code != 0:
                return code, msg
            # TODO extract files from /opt/pht_train/ and calculate hash value

        else:
            return 1, "Image history could not be validated"

    def _compare_image_history(self, master_image: docker.client.ImageCollection,
                               submission_image: docker.client.ImageCollection) -> List[str]:
        """
        Compares the history of the submitted docker image with the master image selected in the ui

        :param master_image: ImageObject representing the selected master image
        :param submission_image: Image object representing the image submitted to pht_train_proposals
        :return: List of difference in the build history between the master image and the proposed train
        :raises: ValueError when the submitted image is not derive from an official master image
        """
        # Get the history of the images
        master_history = master_image.history()
        submission_history = submission_image.history()
        # TODO solve this with set difference maybe
        history_diff = []

        for event in submission_history:
            print(event)
            if event not in master_history:
                history_diff.append(event["CreatedBy"])
        for master_event in master_history:
            if master_event not in submission_history:
                print(master_event)
                if "ENTRYPOINT" in master_event["CreatedBy"]:
                    if not self._validate_entrypoint():
                        raise ValueError("Entrypoint overriding is not allowed")
                else:
                    raise ValueError("The submitted Image is not derived from an accepted base image")
        return history_diff

    def _compare_image_file_system(self, master_image_name: str, submission_image_name: str):

        # TODO check if the correct images get loaded
        container_diff_args = ["container-diff", "diff", f"daemon://{master_image_name}",
                               f"daemon://{submission_image_name}", "--type=file"]
        output = subprocess.run(container_diff_args, capture_output=True)
        file_system_diff = output.stdout.decode().splitlines()
        valid, msg = self._validate_file_system_changes(file_system_diff)
        if valid:
            return 0, "No file system anomalies detected"
        else:
            return 1, "Invalid file system changes detected, files can only be added into " \
                      f"/opt/pht_train, but found {msg}"

    def _validate_history_diff(self, history_diff: list) -> bool:
        # TODO is this even needed?
        return False

    def _validate_entrypoint(self):
        # TODO
        return True

    def _extract_immutable_files(self, img: str, path: str = "../build_dir"):
        """
        Extract the files in /opt/pht_train and hash them to get the hash of immutable files

        :return: file archive
        """
        container = self.client.containers.run(img, detach=True)
        stream, stat = container.get_archive("/opt/pht_train")
        file_obj = BytesIO()
        for f in stream:
            file_obj.write(f)
        file_obj.seek(0)
        tar = tarfile.open(mode="r", fileobj=file_obj)
        tar.extractall(path=path)

    def _get_file_from_container(self, file_path: str):
        pass
        # TODO extract tar archive and generate hash

    def _validate_file_system_changes(self, file_system_diff: List[str]) -> Tuple[bool, str]:
        """
        Validate the file system changes found by the container-diff tools.
        Checks if files have been added at the right location and whether files have been deleted or changed compared
        to the master image

        :param file_system_diff: output generated by the container-diff tool analysing the file system changes between
        two images

        :return: whether the detected changes to the file system are valid
        """
        add_ind = None
        deleted_ind = None
        changed_ind = None
        valid = False
        for ind, content in enumerate(file_system_diff):
            if "These entries have been added" in content:
                add_ind = ind
            elif "These entries have been deleted" in content:
                deleted_ind = ind
            elif "These entries have been changed" in content:
                changed_ind = ind
        # Find the files added to the image file system and make sure they are located exclusively under /opt/pht_train
        if len(file_system_diff[add_ind: deleted_ind]) > 2:
            print("Added files detected.")
            valid = True
            invalid_files = []
            for file in file_system_diff[add_ind + 2: deleted_ind]:
                valid_file, file = self._validate_added_file(file)
                if not valid_file:
                    valid = False
                    invalid_files.append(file)
            invalid_file_string = "\n".join(invalid_files)
            if not valid:
                return False, f"Incorrectly added files:\n{invalid_file_string} "
        # If the length of the deleted files section is greater than two, files have been deleted from the master image
        # -> image invalid
        if len(file_system_diff[deleted_ind: changed_ind]) > 2:
            print("Deleted Files detected")
            valid = False
        # If the length of the deleted files section is greater than two, files have been changed from the master image
        # -> image invalid
        if len(file_system_diff[changed_ind:]) > 2:
            print("Changed files detected")
            valid = False
        if valid:
            print("Validation success!")

        return valid, "Successfully verified file system"

    @staticmethod
    def _validate_added_file(file: str) -> Tuple[bool, str]:
        """
        Checks whether an added file detected by container-diff is located under /opt/pht_train.

        :param file: line of output generated by container diff containing info on the added file
        :return: whether the file is correctly located or not
        """
        path = file.split(" ")[0]
        if len(path) > 1:
            if path.split("/")[1:3] != ["opt", "pht_train"]:
                print(f"Invalid File location found: {path}")
                return False, path
        return True, path

    def _get_image(self, name) -> docker.client.ImageCollection:
        return self.client.images.get(name)


if __name__ == '__main__':
    client = docker.from_env()
    ih = ImageHandler(client)
    test_message = {"master_image": "harbor.personalhealthtrain.de/pht_master/master:buster",
                    "proposal_image": "harbor.personalhealthtrain.de/pht_train_submission/test_valid"}

    print(ih.validate_image(test_message))
